### GET User
GET http://localhost:5000/api/users


### GET User
GET http://localhost:5000/api/users?username=chaynes&password=80LY4V_lpPM3AXq

### POST User
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "jwackle",
    "password": "80LY4V_lpPM3AXq",
    "firstname": "James",
    "lastname": "Wackle",
    "phone": "6808053960",
    "email": "jwackle@example.com",
    "isReviewer": true,
    "isAdmin": false
}

### PUT User
PUT http://localhost:5000/api/users/453
Content-Type: application/json

{
    "id": 453,
    "username": "jmacky",
    "password": "80LY4V_lpPM3AXq",
    "firstname": "James",
    "lastname": "Mack",
    "phone": "6808053960",
    "email": "jmack@example.com",
    "isReviewer": true,
    "isAdmin": false
}

### DELETE User
DELETE http://localhost:5000/api/users/455

### GET Vendors
GET http://localhost:5000/api/vendors

### GET Products
GET http://localhost:5000/api/products

### POST Product
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "partNbr": "978-0-07-249483-8",
    "name": "Modern Rubber Ballz",
    "price": 30.00,
    "unit": "Pair",
    "photoPath": null,
    "vendorId": 15
  }


### GET Requests
GET http://localhost:5000/api/requests

### GET Requests By Status
GET http://localhost:5000/api/requests/status/APPROVED
